export const ADD_CURRENCY    = 'ADD_CURRENCY';
export const DELETE_CURRENCY = 'DELETE_CURRENCY';
export const UPDATE_CURRENCY = 'UPDATE_CURRENCY';

export const AUTO_UPDATE_CURRENCY = 'AUTO_UPDATE_CURRENCY';
// export const UPDATE_PRICE_ERROR = 'UPDATE_PRICE_ERROR';
